#!/usr/bin/env node
// ─────────────────────────────────────────────────────────────────────────
// fetch-spells.mjs  —  one-time spell-data generator (run manually)
//
//   node scripts/fetch-spells.mjs
//
// Pulls the SRD spell lists for every caster class from the dnd5e API and
// writes ../class-spells.js, which defines a global `SPELLS` array (unique
// spells, each tagged with the classes that can cast it). Consumed by the
// Spells section in script.js.
// ─────────────────────────────────────────────────────────────────────────

import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const API = 'https://www.dnd5eapi.co/api/2014';
const CASTERS = ['bard', 'cleric', 'druid', 'paladin', 'ranger', 'sorcerer', 'warlock', 'wizard'];

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = join(__dirname, '..', 'class-spells.js');

async function getJSON(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`);
  return res.json();
}

async function main() {
  // index -> Set(classes), plus the bare list entry (name/level)
  const classesByIndex = new Map();
  for (const c of CASTERS) {
    process.stderr.write(`Listing ${c} spells…\n`);
    const data = await getJSON(`${API}/classes/${c}/spells`);
    for (const s of data.results) {
      if (!classesByIndex.has(s.index)) classesByIndex.set(s.index, new Set());
      classesByIndex.get(s.index).add(c);
    }
  }

  const indexes = [...classesByIndex.keys()].sort();
  process.stderr.write(`\nFetching details for ${indexes.length} unique spells…\n`);

  const spells = [];
  let n = 0;
  for (const index of indexes) {
    const d = await getJSON(`${API}/spells/${index}`);
    const desc = (Array.isArray(d.desc) ? d.desc : [d.desc]).filter(Boolean);
    if (Array.isArray(d.higher_level) && d.higher_level.length) {
      desc.push('At Higher Levels. ' + d.higher_level.join(' '));
    }
    spells.push({
      index: d.index,
      name: d.name,
      level: d.level,                              // 0 = cantrip
      school: d.school?.name || '',
      casting_time: d.casting_time || '',
      range: d.range || '',
      components: Array.isArray(d.components) ? d.components.join(', ') : '',
      material: d.material || '',
      duration: d.duration || '',
      concentration: !!d.concentration,
      ritual: !!d.ritual,
      classes: [...classesByIndex.get(index)].sort(),
      desc: desc.join('\n').trim(),
    });
    if (++n % 25 === 0) process.stderr.write(`  ${n}/${indexes.length}\n`);
  }

  spells.sort((a, b) => a.level - b.level || a.name.localeCompare(b.name));

  const banner =
    '// AUTO-GENERATED by scripts/fetch-spells.mjs — do not edit by hand.\n' +
    '// Source: dnd5e API (https://www.dnd5eapi.co) — SRD spells for all caster classes.\n' +
    '// Re-run: node scripts/fetch-spells.mjs\n\n';
  await writeFile(OUT, banner + `const SPELLS = ${JSON.stringify(spells, null, 1)};\n`, 'utf8');
  process.stderr.write(`\nWrote ${OUT} — ${spells.length} spells.\n`);
}

main().catch((err) => { process.stderr.write(`ERROR: ${err.message}\n`); process.exit(1); });
